#!/bin/bash

# DNS Testing Commands Reference for maptimize-prod.campaign.adobe.com
# This file contains all commands used for comprehensive DNS testing

echo "=== DNS TESTING COMMANDS REFERENCE ==="
echo ""
echo "Run these commands to perform your own DNS testing:"
echo ""

# Basic Resolution Tests
echo "### BASIC RESOLUTION TESTS ###"
echo ""
echo "1. nslookup test:"
echo "   nslookup maptimize-prod.campaign.adobe.com"
echo ""
echo "2. dig test:"
echo "   dig maptimize-prod.campaign.adobe.com"
echo ""
echo "3. host verbose test:"
echo "   host -v maptimize-prod.campaign.adobe.com"
echo ""

# Nameserver Information
echo "### NAMESERVER INFORMATION ###"
echo ""
echo "1. Query nameservers:"
echo "   dig campaign.adobe.com NS +short"
echo ""
echo "2. Detailed nameserver info:"
echo "   dig campaign.adobe.com NS"
echo ""
echo "3. SOA record:"
echo "   dig campaign.adobe.com SOA +short"
echo ""

# Parent Domain Testing
echo "### PARENT DOMAIN TESTING ###"
echo ""
echo "1. Resolve parent domain:"
echo "   dig campaign.adobe.com +noall +answer"
echo ""
echo "2. MX records:"
echo "   dig campaign.adobe.com MX +noall +answer"
echo ""
echo "3. TXT records (SPF):"
echo "   dig campaign.adobe.com TXT +noall +answer"
echo ""

# Multi-DNS Server Testing
echo "### MULTI-DNS SERVER TESTING ###"
echo ""
echo "1. Google DNS (may be blocked in restricted networks):"
echo "   dig @8.8.8.8 maptimize-prod.campaign.adobe.com +short"
echo ""
echo "2. CloudFlare DNS (may be blocked in restricted networks):"
echo "   dig @1.1.1.1 maptimize-prod.campaign.adobe.com +short"
echo ""
echo "3. Authoritative nameserver:"
echo "   dig @ns-1122.awsdns-12.org campaign.adobe.com A +noall +answer"
echo ""

# DNS Trace Testing
echo "### DNS TRACE TESTING ###"
echo ""
echo "1. Full trace (shows resolution path):"
echo "   dig maptimize-prod.campaign.adobe.com +trace"
echo ""
echo "2. Trace to parent domain:"
echo "   dig campaign.adobe.com +trace"
echo ""

# Response Code and Details
echo "### RESPONSE CODES AND DETAILS ###"
echo ""
echo "1. Check response code:"
echo "   dig maptimize-prod.campaign.adobe.com +nocmd +noall +comments"
echo ""
echo "2. Full answer section:"
echo "   dig maptimize-prod.campaign.adobe.com A +noall +answer"
echo ""

# Verification Commands (AFTER DNS record creation)
echo "### VERIFICATION COMMANDS (after DNS creation) ###"
echo ""
echo "1. Verify record exists:"
echo "   dig maptimize-prod.campaign.adobe.com @10.98.3.19 +short"
echo ""
echo "2. Check TTL value:"
echo "   dig maptimize-prod.campaign.adobe.com +noall +answer"
echo ""
echo "3. Verify IP address (should be 52.213.19.55):"
echo "   dig maptimize-prod.campaign.adobe.com +short | grep 52.213.19.55"
echo ""
echo "4. Query specific nameserver:"
echo "   dig @ns-1122.awsdns-12.org maptimize-prod.campaign.adobe.com +short"
echo ""

# Troubleshooting Commands
echo "### TROUBLESHOOTING COMMANDS ###"
echo ""
echo "1. Check system resolver configuration:"
echo "   cat /etc/resolv.conf  # On Linux/Unix"
echo "   scutil --dns          # On macOS"
echo ""
echo "2. Detailed nslookup debug:"
echo "   nslookup -debug campaign.adobe.com"
echo ""
echo "3. Network connectivity test:"
echo "   ping -c 4 52.213.19.55"
echo ""
echo "4. Check specific resolver:"
echo "   dig @10.98.3.19 maptimize-prod.campaign.adobe.com +short"
echo ""

echo ""
echo "=== EXPECTED RESULTS AFTER DNS CREATION ==="
echo ""
echo "Expected resolution:"
echo "  $ dig maptimize-prod.campaign.adobe.com +short"
echo "  52.213.19.55"
echo ""
echo "Expected TTL:"
echo "  Around 300 seconds (5 minutes) initially"
echo "  May vary based on Route53 configuration"
echo ""
echo "Expected nameserver:"
echo "  Should resolve through AWS Route53 nameservers"
echo ""
