"""
Test configuration for JIRA reporter tests.

Contains test JIRA tickets and sample data for consistent testing.
"""

# Test JIRA tickets
TEST_JIRA_TICKETS = {
    "CPGNREQ": "CPGNREQ-180248",  # Test ticket in Campaign Requests
    "CSOPM": "CPGNREQ-180375",  # Test ticket acting as CSOPM (has CSO comment with exigence URL)
}

# Sample channel configurations for testing
TEST_CHANNELS = {
    "with_exigence_id": {
        "channel_id": "C_TEST_001",
        "channel_name": "cso_202401010001_test_customer_78155",
        "customer_name": "Test Customer",
        "jira_ticket": "",  # To be discovered
        "archived_at": 1704067200,  # 2024-01-01
        "exigence_id": "78155",
        "exigence_url": "https://adobe.app.exigence.io/secure/index.html#/events/78155/situationroom",
    },
    "with_existing_ticket": {
        "channel_id": "C_TEST_002",
        "channel_name": "cso_202401020001_test_adobe_12345",
        "customer_name": "Test Adobe",
        "jira_ticket": TEST_JIRA_TICKETS["CPGNREQ"],
        "archived_at": 1704153600,  # 2024-01-02
    },
    "non_cso_channel": {
        "channel_id": "C_TEST_003",
        "channel_name": "general-discussion",
        "customer_name": "",
        "jira_ticket": "",
        "archived_at": 1704240000,  # 2024-01-03
    },
    "cso_no_ticket": {
        "channel_id": "C_TEST_004",
        "channel_name": "cso_202401040001_missing_ticket",
        "customer_name": "Missing Ticket Customer",
        "jira_ticket": "NOT YET AVAILABLE",
        "archived_at": 1704326400,  # 2024-01-04
    },
}

# Sample Slack messages for testing
TEST_MESSAGES = [
    {
        "user": "U_TEST_001",
        "text": "We're experiencing authentication issues with the campaign service",
        "ts": "1704067200.100001",
    },
    {
        "user": "U_TEST_002",
        "text": "I see multiple 401 errors in the logs",
        "ts": "1704067260.100002",
    },
    {
        "user": "U_TEST_003",
        "text": "Checking the certificate status now",
        "ts": "1704067320.100003",
    },
    {
        "user": "U_TEST_002",
        "text": "Certificate expired yesterday at midnight",
        "ts": "1704067380.100004",
    },
    {
        "user": "U_TEST_001",
        "text": "Renewing certificate and redeploying",
        "ts": "1704067440.100005",
    },
    {
        "user": "U_TEST_003",
        "text": "Service is back online, authentication working",
        "ts": "1704067500.100006",
    },
]

# Expected report sections
EXPECTED_REPORT_SECTIONS = [
    "h3. Executive Summary",
    "h3. People Involved",
    "h3. Incident Timeline",
    "h3. Technical Analysis",
    "h3. Impact Assessment",
    "h3. Resolution & Mitigation",
    "h3. JIRA Tickets & Work Done",
    "h3. Next Steps",
    "h3. References",
]

# Test report template
TEST_REPORT_TEMPLATE = """h2. Ketchup Automated Incident Report

*Channel*: {channel_name} (ID: {channel_id})
*Customer*: {customer_name}
*Generated*: 2024-01-01 00:00:00 UTC

----

h3. Executive Summary
Authentication service experienced a certificate expiration causing login failures for campaign services.

h3. People Involved
- U_TEST_001: Incident commander, managed resolution
- U_TEST_002: Identified root cause
- U_TEST_003: Implemented fix

h3. Incident Timeline
- 2024-01-01 00:00:00 UTC: Authentication issues reported
- 2024-01-01 00:01:00 UTC: 401 errors identified in logs
- 2024-01-01 00:02:00 UTC: Certificate check initiated
- 2024-01-01 00:03:00 UTC: Expired certificate identified
- 2024-01-01 00:04:00 UTC: Certificate renewal started
- 2024-01-01 00:05:00 UTC: Service restored

h3. Technical Analysis
Root cause: SSL certificate expired at midnight causing authentication failures.

h3. Impact Assessment
All campaign services were unable to authenticate for approximately 5 minutes.

h3. Resolution & Mitigation
Certificate was renewed and service redeployed. Monitoring added for certificate expiration.

h3. JIRA Tickets & Work Done
Related ticket: {jira_ticket}

h3. Next Steps
- Implement automated certificate renewal
- Add 30-day expiration alerts

h3. References
- Support ticket: #12345
- Channel: #{channel_name}

----

_This report was automatically generated by Ketchup when the channel was archived._"""
