"""
Test JIRA reporter authentication integration
"""

import os
from unittest.mock import AsyncMock, patch

import pytest

from jira_reporter.jira_service import JiraService
from packages.core.typed_di_integration import cleanup_container, get_container


@pytest.mark.asyncio
async def test_jira_service_with_ims_authentication():
    """Test that JiraService properly uses IMS token for authentication."""
    try:
        # Initialize container
        container = await get_container()

        # Get required services using TypedDI
        from packages.integrations.ims_token_manager import IMSTokenManager
        from packages.secrets.manager import SecretsManager

        secrets_manager = await container.aget(SecretsManager)
        ims_token_manager = await container.aget(IMSTokenManager)

        # Create JIRA service
        jira_service = JiraService(
            secrets_manager=secrets_manager, ims_token_manager=ims_token_manager
        )

        # Test ticket
        ticket_id = "CPGNREQ-180375"
        comment_text = "Test comment from JIRA reporter with IMS authentication"

        # Mock the httpx client to check headers
        with patch("jira_reporter.jira_service.httpx.AsyncClient") as mock_client:
            mock_response = AsyncMock()
            mock_response.status_code = 200
            mock_response.json.return_value = {
                "jsonrpc": "2.0",
                "id": f"jira-reporter-{ticket_id}",
                "result": {"content": [{"type": "text", "text": '{"success": true}'}]},
            }

            mock_client_instance = AsyncMock()
            mock_client_instance.post.return_value = mock_response
            mock_client.return_value.__aenter__.return_value = mock_client_instance

            # Call the method
            success = await jira_service.post_comment_to_ticket(
                jira_ticket_id=ticket_id, comment_text=comment_text
            )

            # Verify the call was made with proper headers
            assert mock_client_instance.post.called
            call_args = mock_client_instance.post.call_args

            # Check URL
            assert call_args[0][0] == "http://mcp-jira:8081/message"

            # Check headers include Authorization
            headers = call_args[1]["headers"]
            assert "Authorization" in headers
            assert headers["Authorization"].startswith("Bearer ")
            assert len(headers["Authorization"]) > 10  # Has actual token

            # Check JSON-RPC format
            payload = call_args[1]["json"]
            assert payload["method"] == "tools/call"
            assert payload["params"]["name"] == "add_jira_comment"
            assert payload["params"]["arguments"]["issueIdOrKey"] == ticket_id

            assert success is True

    finally:
        await cleanup_container()


@pytest.mark.asyncio
@pytest.mark.integration
async def test_jira_reporter_full_integration():
    """Full integration test posting to real JIRA ticket."""
    if not os.getenv("RUN_JIRA_INTEGRATION_TESTS"):
        pytest.skip("Set RUN_JIRA_INTEGRATION_TESTS=true to run this test")

    try:
        container = await get_container()

        # Get required services using TypedDI
        from packages.integrations.ims_token_manager import IMSTokenManager
        from packages.secrets.manager import SecretsManager

        secrets_manager = await container.aget(SecretsManager)
        ims_token_manager = await container.aget(IMSTokenManager)

        # Create JIRA service
        jira_service = JiraService(
            secrets_manager=secrets_manager, ims_token_manager=ims_token_manager
        )

        # Test ticket
        ticket_id = "CPGNREQ-180375"
        comment_text = "✅ **JIRA Reporter Integration Test Success**\n\nThis comment confirms that the JIRA reporter service is working correctly with:\n- ✓ IMS token authentication via DI container\n- ✓ MCP service integration\n- ✓ Proper JSON-RPC formatting\n\nGenerated by automated test at 2025-07-07"

        # Post comment
        success = await jira_service.post_comment_to_ticket(
            jira_ticket_id=ticket_id, comment_text=comment_text
        )

        assert success is True, "Failed to post comment to JIRA"

    finally:
        await cleanup_container()
