#!/usr/bin/env python3
"""
Real integration test to post to CPGNREQ-180375 and verify JIRA reporter functionality
Step-by-step approach to identify and fix issues
"""

import asyncio
import os
import sys
import time
from unittest.mock import AsyncMock, MagicMock

# Import test configuration
sys.path.append(os.path.join(os.path.dirname(__file__), "../../unit/test_jira_reporter"))
from test_config import TEST_JIRA_TICKETS, TEST_MESSAGES


async def test_step_1_basic_jira_mcp_tool():
    """Step 1: Test basic JIRA MCP tool functionality"""
    print("🔧 STEP 1: Testing JIRA MCP tool...")

    try:
        from packages.core.typed_di_integration import get_container
        from packages.integrations.mcp_client import MCPClient

        print("🔧 Initializing DI Container...")
        container = await get_container()
        print("✅ DI Container initialized")

        print("🔧 Getting MCP client from container...")
        mcp_client = await container.aget(MCPClient)
        print("✅ MCP client retrieved")

        target_ticket = TEST_JIRA_TICKETS["CSOPM"]  # CPGNREQ-180375
        print(f"🎯 Testing MCP client with ticket {target_ticket}...")

        # Test adding a comment using MCP client directly
        test_comment = f"""
h2. Ketchup JIRA Reporter Test

*Channel*: test_acc_cso_12345 (ID: C094DQY7HLH)
*Customer*: Test Account Customer
*Generated*: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}

----

h3. Test Summary
This is a test comment from the Ketchup JIRA Reporter integration test using MCP client.

h3. Test Details
- Channel ID: C094DQY7HLH
- Channel Name: test_acc_cso_12345
- Exigence ID: 12345
- Test Timestamp: {int(time.time())}

h3. Next Steps
This test verifies the MCP client can successfully post comments to JIRA tickets.

----

_This is a test comment generated by the Ketchup JIRA Reporter integration test._
"""

        print("💬 Attempting to add comment via MCP client...")

        # Use the proper MCP client method to add a JIRA comment
        success = await mcp_client.create_issue_comment(
            issue_key=target_ticket, comment=test_comment
        )

        print(f"📄 MCP client success: {success}")

        if success:
            print("🎉 SUCCESS! Test comment posted via MCP client!")
            print(f"✅ Check {target_ticket} for the test comment")
            return True
        else:
            print("❌ FAILED! Could not post comment via MCP client")
            return False

    except Exception as e:
        print(f"💥 ERROR in step 1: {e}")
        import traceback

        traceback.print_exc()
        return False


async def test_step_2_report_generation():
    """Step 2: Test report generation with mock data"""
    print("\n🤖 STEP 2: Testing report generation...")

    try:
        from jira_reporter.report_generator import ReportGenerator

        # Create mock OpenAI handler
        mock_openai_handler = MagicMock()
        mock_openai_handler.generate_response = AsyncMock(
            return_value=f"""
h2. Ketchup Automated Incident Report

*Channel*: test_acc_cso_12345 (ID: C094DQY7HLH)
*Customer*: Test Account Customer
*Generated*: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}

----

h3. Executive Summary
Integration test for JIRA reporter functionality using real channel C094DQY7HLH.

h3. People Involved
- Test User 1: Reported authentication issues
- Test User 2: Identified certificate problems
- Test User 3: Implemented certificate fix

h3. Incident Timeline
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(int(time.time()) - 300))}: Authentication issues reported
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(int(time.time()) - 240))}: Multiple 401 errors identified
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(int(time.time()) - 180))}: Certificate check initiated
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(int(time.time()) - 120))}: Expired certificate found
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(int(time.time()) - 60))}: Certificate renewed
- {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}: Service restored

h3. Technical Analysis
SSL certificate expired causing authentication failures for campaign services.

h3. Resolution & Mitigation
Certificate was renewed and services redeployed successfully.

h3. JIRA Tickets & Work Done
Related tickets: {TEST_JIRA_TICKETS["CSOPM"]}

h3. Next Steps
- Monitor certificate expiration dates
- Implement automated renewal process

h3. References
- Channel: #test_acc_cso_12345
- Exigence: https://adobe.app.exigence.io/secure/index.html#/events/12345/situationroom

----

_This report was automatically generated by Ketchup JIRA Reporter integration test._
"""
        )

        # Create mock message operations
        mock_msg_ops = MagicMock()
        mock_msg_ops.fetch_channel_messages = AsyncMock(return_value=TEST_MESSAGES)

        report_generator = ReportGenerator(
            openai_handler=mock_openai_handler, channel_msg_ops=mock_msg_ops
        )

        channel_data = {
            "channel_id": "C094DQY7HLH",
            "channel_name": "test_acc_cso_12345",
            "customer_name": "Test Account Customer",
            "jira_ticket": TEST_JIRA_TICKETS["CSOPM"],
            "archived_at": int(time.time()) - 3600,
            "exigence_id": "12345",
            "exigence_url": "https://adobe.app.exigence.io/secure/index.html#/events/12345/situationroom",
        }

        print("📝 Generating incident report...")
        report_text = await report_generator.generate_report(
            channel_id="C094DQY7HLH", channel_metadata=channel_data
        )

        if report_text and len(report_text) > 100:
            print("✅ Report generated successfully!")
            print(f"📄 Report length: {len(report_text)} characters")

            # Now post this real report to JIRA
            print(f"\n🎯 Posting generated report to {TEST_JIRA_TICKETS['CSOPM']}...")

            from jira_reporter.jira_service import JiraService

            mock_secrets_manager = MagicMock()
            mock_secrets_manager.get_secret_value = AsyncMock(
                return_value={
                    "jira_username": "test",
                    "jira_password": "test",
                    "jira_server": "https://jira.corp.adobe.com",
                }
            )

            # Override MCP URL for local testing
            os.environ["MCP_BASE_URL"] = "http://localhost:8081"

            jira_service = JiraService(
                secrets_manager=mock_secrets_manager, ims_token_manager=MagicMock()
            )
            success = await jira_service.post_comment_to_ticket(
                jira_ticket_id=TEST_JIRA_TICKETS["CSOPM"], comment_text=report_text
            )

            if success:
                print("🎉 SUCCESS! Generated report posted to JIRA!")
                return True
            else:
                print("❌ FAILED! Could not post generated report")
                return False
        else:
            print("❌ FAILED! Report generation failed")
            return False

    except Exception as e:
        print(f"💥 ERROR in step 2: {e}")
        import traceback

        traceback.print_exc()
        return False


async def run_all_tests():
    """Run all test steps in sequence"""
    print("🚀 JIRA REPORTER REAL INTEGRATION TEST")
    print("=" * 70)
    print(f"Target ticket: {TEST_JIRA_TICKETS['CSOPM']} (CPGNREQ-180375)")
    print("Test channel: C094DQY7HLH (test_acc_cso_12345)")
    print("=" * 70)

    # Step 1: Basic JIRA MCP tool testing
    step1_success = await test_step_1_basic_jira_mcp_tool()

    if step1_success:
        # Step 2: Full report generation and posting
        step2_success = await test_step_2_report_generation()

        if step2_success:
            print("\n🎉 ALL TESTS PASSED!")
            print("=" * 70)
            print(f"✅ Check JIRA ticket {TEST_JIRA_TICKETS['CSOPM']} for comments!")
            print("✅ JIRA reporter is working correctly!")
            print("=" * 70)
            return True

    print("\n💥 SOME TESTS FAILED!")
    return False


if __name__ == "__main__":
    print("⚠️  WARNING: This will post real comments to CPGNREQ-180375!")
    print("⚠️  Make sure you want to proceed...")
    print()

    try:
        success = asyncio.run(run_all_tests())
        if success:
            print(
                f"\n🚀 Integration test completed! Check {TEST_JIRA_TICKETS['CSOPM']} for comments!"
            )
            sys.exit(0)
        else:
            print("\n💥 Integration test failed!")
            sys.exit(1)
    except Exception as e:
        print(f"\n💥 Test execution failed: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
