#!/usr/bin/env python3
"""
Integration test for MCP JIRA service direct HTTP calls
Tests within the Makefile framework
"""

import json
import os
import time

import pytest
import requests
from dotenv import load_dotenv

# Load environment variables from infrastructure/.env
load_dotenv(os.path.join(os.path.dirname(__file__), "../../../infrastructure/.env"))

# Test configuration
MCP_URL = "http://localhost:8081"
TARGET_TICKET = "CPGNREQ-180375"  # Our test "CSOPM" ticket


def test_mcp_service_health():
    """Test MCP service health endpoint"""
    print("🔧 Testing MCP service health...")

    try:
        response = requests.get(f"{MCP_URL}/health", timeout=5)
        if response.status_code == 200:
            health_data = response.json()
            print(f"✅ MCP service is healthy: {health_data}")
            assert health_data.get("status") == "ok"
        else:
            print(f"❌ MCP service unhealthy: {response.status_code}")
            assert False, f"MCP service returned {response.status_code}"
    except Exception as e:
        print(f"💥 ERROR: {e}")
        assert False, f"MCP service connection failed: {e}"


def test_mcp_add_jira_comment():
    """Test MCP add_jira_comment tool directly via HTTP"""
    print("🔧 Testing MCP add_jira_comment tool...")

    # Mock the JIRA auth token from environment (using IPASS=true)
    jira_token = os.getenv("JIRA_IMS_TOKEN")
    if not jira_token:
        pytest.skip("JIRA_IMS_TOKEN not found in environment")

    # Create test comment
    test_comment = f"""
h2. MCP Integration Test Comment

*Test Timestamp*: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}
*Test ID*: {int(time.time())}

----

h3. Test Details
This is an integration test of the MCP service add_jira_comment tool within the Makefile framework.

h3. System Information
- MCP Service: {MCP_URL}
- Tool: add_jira_comment
- Target Ticket: {TARGET_TICKET}

----

_Generated by MCP integration test via Makefile_
"""

    # Prepare the JSON-RPC request
    request_data = {
        "jsonrpc": "2.0",
        "id": "test-integration",
        "method": "tools/call",
        "params": {
            "name": "add_jira_comment",
            "arguments": {
                "issueIdOrKey": TARGET_TICKET,
                "comment": {"body": test_comment},
            },
        },
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {jira_token}",
    }

    try:
        print(f"📤 Sending request to {MCP_URL}/message")
        response = requests.post(
            f"{MCP_URL}/message", json=request_data, headers=headers, timeout=10
        )

        print(f"📥 Response status: {response.status_code}")
        response_text = response.text
        print(f"📄 Response body: {response_text}")

        if response.status_code == 200:
            try:
                response_data = json.loads(response_text)
                if "result" in response_data:
                    print("🎉 SUCCESS! MCP add_jira_comment tool works!")
                    print(f"✅ Check {TARGET_TICKET} for the test comment")
                else:
                    print("❌ FAILED! No result in response")
                    print(f"Response: {response_data}")
                    assert False, f"No result in MCP response: {response_data}"
            except json.JSONDecodeError as e:
                print(f"❌ FAILED! Invalid JSON response: {e}")
                assert False, f"Invalid JSON response from MCP: {response_text}"
        else:
            print(f"❌ FAILED! HTTP {response.status_code}: {response_text}")
            assert False, f"MCP service returned {response.status_code}: {response_text}"

    except Exception as e:
        print(f"💥 ERROR: {e}")
        assert False, f"MCP request failed: {e}"


def test_mcp_list_jira_projects():
    """Test MCP list_jira_projects tool directly via HTTP"""
    print("🔧 Testing MCP list_jira_projects tool...")

    # Mock the JIRA auth token from environment
    jira_token = os.getenv("JIRA_IMS_TOKEN")
    if not jira_token:
        pytest.skip("JIRA_IMS_TOKEN not found in environment")

    # Prepare the JSON-RPC request for list_jira_projects
    request_data = {
        "jsonrpc": "2.0",
        "id": "test-list-projects",
        "method": "tools/call",
        "params": {
            "name": "list_jira_projects",
            "arguments": {},
        },
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {jira_token}",
    }

    try:
        print(f"📤 Sending request to {MCP_URL}/message")
        response = requests.post(
            f"{MCP_URL}/message", json=request_data, headers=headers, timeout=15
        )

        print(f"📥 Response status: {response.status_code}")

        if response.status_code == 200:
            try:
                response_data = json.loads(response.text)
                if "result" in response_data:
                    content = response_data.get("result", {}).get("content", [])
                    if content and len(content) > 0:
                        text_content = content[0].get("text", "{}")
                        parsed = json.loads(text_content)
                        if parsed.get("success"):
                            projects = parsed.get("data", [])
                            print(f"🎉 SUCCESS! Found {len(projects)} JIRA projects")
                            if projects:
                                print(
                                    f"   First project: {projects[0].get('key', 'N/A')} - {projects[0].get('name', 'N/A')}"
                                )
                            assert isinstance(projects, list), "Projects should be a list"
                        else:
                            print(
                                f"⚠️ API returned success=False: {parsed.get('message', 'Unknown')}"
                            )
                    else:
                        print("✅ MCP list_jira_projects returned empty content (may be expected)")
                else:
                    print("❌ FAILED! No result in response")
                    print(f"Response: {response_data}")
                    assert False, f"No result in MCP response: {response_data}"
            except json.JSONDecodeError as e:
                print(f"❌ FAILED! Invalid JSON response: {e}")
                assert False, f"Invalid JSON response from MCP: {response.text}"
        else:
            print(f"❌ FAILED! HTTP {response.status_code}: {response.text}")
            assert False, f"MCP service returned {response.status_code}: {response.text}"

    except Exception as e:
        print(f"💥 ERROR: {e}")
        assert False, f"MCP request failed: {e}"


def test_mcp_integration_flow():
    """Test complete MCP integration flow"""
    print("\n🚀 MCP INTEGRATION TEST FLOW")
    print("=" * 70)
    print(f"Testing MCP tools for ticket {TARGET_TICKET}")
    print("=" * 70)

    # Step 1: Health check
    test_mcp_service_health()

    # Step 2: List projects functionality
    test_mcp_list_jira_projects()

    # Step 3: Add comment functionality
    test_mcp_add_jira_comment()

    print("\n🎉 ALL MCP INTEGRATION TESTS PASSED!")
    print("=" * 70)
    print("✅ MCP list_jira_projects tool is working correctly!")
    print("✅ MCP add_jira_comment tool is working correctly!")
    print(f"✅ Check {TARGET_TICKET} for the test comment")
    print("=" * 70)


if __name__ == "__main__":
    test_mcp_integration_flow()
