# AWS-specific protocols for typed DI migration
# DO NOT EDIT - Generated by extract_service_interfaces.py

from typing import Protocol, Any, Dict, Optional

# Placeholder types for missing dependencies - fallback to Any for all undefined types
SecretsManager = Any
SlackConfig = Any

class VersionComparatorProtocol(Protocol):
    """Protocol for VersionComparator."""

    def parse_version(tag: str) -> Optional[tuple]: ...

    def should_preserve_image(cls, repository_name: str, tag: str) -> bool: ...



class SecretStoreProtocol(Protocol):
    """Protocol for SecretStore."""

    async def get_secret(self, secret_name: str) -> Dict[str, Any]: ...


class SecretsManagerProtocol(Protocol):
    """Protocol for SecretsManager."""

    async def get_secret_value(self, secret_id: str) -> str: ...

    async def get_secret_dict(self, secret_id: str) -> Dict[str, Any]: ...

    async def put_secret_value(self, secret_id: str, secret_value: str) -> None: ...

    async def update_secret(self, secret_id: str, secret_dict: Dict[str, Any]) -> None: ...

    async def delete_secret(self, secret_id: str) -> None: ...


class KetchupConfigProtocol(Protocol):
    """Protocol for KetchupConfig."""

    def get_slack_config(self) -> SlackConfig: ...

    def get_aws_region(self) -> str: ...

    def get_dynamodb_table_name(self) -> str: ...

    def get_secrets_name(self) -> str: ...

    def get_log_level(self) -> str: ...

    def get_feature_flag(self, flag_name: str) -> bool: ...