# Core infrastructure protocols for typed DI migration
# DO NOT EDIT - Generated by extract_service_interfaces.py

from dataclasses import dataclass
from typing import (
    Any,
    Awaitable,
    Callable,
    Dict,
    List,
    Literal,
    Optional,
    Protocol,
    Tuple,
    Type,
    TypeVar,
)

T = TypeVar("T")

# Type aliases for missing types
Factory = Callable[..., T]
AsyncFactory = Callable[..., Awaitable[T]]
Provider = Callable[[], T]
AsyncProvider = Callable[[], Awaitable[T]]
DependencySpec = Any


# Add any additional missing types that might appear later
def __getattr__(name: str) -> Any:
    """Fallback for any undefined type names - return Any."""
    return Any


@dataclass(frozen=True)
class InitializationStats:
    """Statistics captured during registry initialization."""

    service_order: List[Type]
    timings: Dict[Type, float]
    failures: List[Tuple[Type, Exception]]
    retries: Dict[Type, int]
    total_duration: float
    deterministic_tie_breaks: List[Tuple[Type, Type]]


@dataclass
class ServiceRegistration:
    """Internal service registration record."""

    service_type: Type[Any]
    factory: Callable[[Any], Any]  # Can be sync or async
    dependencies: List[DependencySpec]
    lifetime: Literal["singleton"]
    qualifier: Optional[str]
    registration_index: int  # For deterministic tie-breaking
    is_async: bool


class DIContainerProtocol(Protocol):
    """Protocol for DIContainer."""

    async def initialize(self) -> None: ...

    async def cleanup(self) -> None: ...

    def get(self, dependency_type: Type[T]) -> T: ...

    def get_by_name(self, name: str): ...

    def is_initialized(self) -> bool: ...


class TypedDIProtocol(Protocol):
    """Protocol for TypedDI."""

    def get(self, dependency_type: Type[T]) -> T: ...

    async def aget(self, dependency_type: Type[T]) -> T: ...

    def get_by_name(self, name: str): ...

    def is_available(self, dependency_type: Type[T]) -> bool: ...

    def is_initialized(self) -> bool: ...

    def register_service(
        self, factory: Callable[..., T], dependencies: List[Type], service_type: Type[T] = None
    ): ...

    async def initialize(self) -> InitializationStats: ...

    async def cleanup(self): ...


class FallbackRegistryProtocol(Protocol):
    """Protocol for FallbackRegistry."""

    def register_service(self, service: Any) -> None: ...

    def register_service_with_type(self, service: Any, service_type: Type[T]) -> None: ...

    def get_service(self, service_type: Type[T]) -> T: ...

    def get_service_by_name(self, service_name: str) -> Any: ...

    def register_callable(
        self, service_callable: Callable, dependencies: List[Type[Any]], service_type: Type[T]
    ) -> None: ...

    def initialize(self) -> None: ...

    def is_available(self, service_type: Type[T]) -> bool: ...


class DistributedLockProtocol(Protocol):
    """Protocol for DistributedLock."""

    async def acquire_lock(self, resource_id: str, timeout_seconds: int = None): ...


class HTTPClientProtocol(Protocol):
    """Protocol for HTTPClient."""

    async def get(
        self, url: str, headers: Dict[str, str] = None, params: Dict[str, Any] = None
    ) -> Dict[str, Any]: ...

    async def post(
        self,
        url: str,
        data: Dict[str, Any] = None,
        json: Dict[str, Any] = None,
        headers: Dict[str, str] = None,
    ) -> Dict[str, Any]: ...

    async def put(
        self,
        url: str,
        data: Dict[str, Any] = None,
        json: Dict[str, Any] = None,
        headers: Dict[str, str] = None,
    ) -> Dict[str, Any]: ...

    async def delete(self, url: str, headers: Dict[str, str] = None) -> Dict[str, Any]: ...

    async def patch(
        self,
        url: str,
        data: Dict[str, Any] = None,
        json: Dict[str, Any] = None,
        headers: Dict[str, str] = None,
    ) -> Dict[str, Any]: ...
