# Business service protocols for typed DI migration
# DO NOT EDIT - Generated by extract_service_interfaces.py

from typing import Any, Dict, List, Optional, Protocol, Tuple

# Placeholder types for missing dependencies - fallback to Any for all undefined types
ChannelMetadata = Any
AccessRequest = Any
ValidationResult = Any
RateLimitResult = Any
ChannelInfoOps = Any
FeatureCommandParams = Any


class ChannelMetadataServiceProtocol(Protocol):
    """Protocol for ChannelMetadataService."""

    async def update_metadata(self, body: Dict[str, Any]) -> Dict[str, Any]: ...

    async def fetch_slack_channels(self, workspace: str) -> List[Dict[str, Any]]: ...

    async def save_slack_channels_to_db(self, channels: List[Dict[str, Any]]) -> None: ...

    async def get_updated_channels_data(self) -> Tuple[int, int]: ...


class ChannelDynamoDBServiceProtocol(Protocol):
    """Protocol for ChannelDynamoDBService."""

    async def save_channels(self, channels: List[ChannelMetadata]) -> int: ...

    async def get_channels(self, channel_ids: List[str]) -> List[ChannelMetadata]: ...

    async def save_channel_metadata(self, channel_metadata: ChannelMetadata) -> bool: ...

    async def get_channel_metadata(self, channel_id: str) -> Optional[ChannelMetadata]: ...

    async def list_all_channels(self) -> List[ChannelMetadata]: ...

    async def list_monitored_channels(self) -> List[ChannelMetadata]: ...

    async def check_if_monitoring(self, channel_id: str) -> bool: ...

    async def get_user_channels(self, user_id: str) -> List[str]: ...

    async def get_user_channels_with_metadata(
        self, user_id: str
    ) -> List[Tuple[str, ChannelMetadata]]: ...

    async def get_channels_by_name(self, channel_name: str) -> List[ChannelMetadata]: ...

    async def search_channels(
        self, search_term: str, limit: int = None
    ) -> List[ChannelMetadata]: ...

    async def count_total_channels(self) -> int: ...

    async def count_monitored_channels(self) -> int: ...

    async def get_all_workspaces(self) -> List[str]: ...

    async def get_workspace_channels(self, workspace: str) -> List[ChannelMetadata]: ...

    async def bulk_update_channels(self, updates: List[Tuple[str, Dict[str, Any]]]) -> int: ...

    async def delete_channel(self, channel_id: str) -> bool: ...

    async def cleanup_old_channels(self, days_old: int = None) -> int: ...


class AccessRequestServiceProtocol(Protocol):
    """Protocol for AccessRequestService."""

    async def create_request(self, access_request: AccessRequest) -> AccessRequest: ...

    async def get_request(self, request_id: str) -> Optional[AccessRequest]: ...

    async def approve_request(self, request_id: str, approved_by: str) -> AccessRequest: ...

    async def deny_request(
        self, request_id: str, denied_by: str, reason: str = None
    ) -> AccessRequest: ...

    async def list_pending_requests(self) -> List[AccessRequest]: ...

    async def list_user_requests(self, user_id: str) -> List[AccessRequest]: ...


class KetchupJIRAClientProtocol(Protocol):
    """Protocol for KetchupJIRAClient."""

    async def create_issue(
        self,
        project_key: str,
        summary: str,
        description: str,
        issue_type: str = None,
        assignee: str = None,
        labels: List[str] = None,
        epic_link: str = None,
        **kwargs,
    ) -> Dict[str, Any]: ...

    async def get_issue(self, issue_key: str, fields: List[str] = None) -> Dict[str, Any]: ...

    async def update_issue(self, issue_key: str, fields: Dict[str, Any]) -> Dict[str, Any]: ...

    async def search_issues(
        self, jql: str, fields: List[str] = None, max_results: int = None
    ) -> Dict[str, Any]: ...

    async def get_projects(self) -> List[Dict[str, Any]]: ...

    async def get_issue_types(self, project_key: str = None) -> List[Dict[str, Any]]: ...

    async def get_users(self, query: str = None) -> List[Dict[str, Any]]: ...

    async def add_comment(self, issue_key: str, comment: str) -> Dict[str, Any]: ...

    async def add_attachment(
        self, issue_key: str, file_path: str, filename: str = None
    ) -> Dict[str, Any]: ...

    async def create_epic(
        self, project_key: str, summary: str, description: str = None
    ) -> Dict[str, Any]: ...

    async def link_issue_to_epic(self, issue_key: str, epic_key: str) -> None: ...

    async def get_project_versions(self, project_key: str) -> List[Dict[str, Any]]: ...

    async def get_project_components(self, project_key: str) -> List[Dict[str, Any]]: ...


class JIRAReporterServiceProtocol(Protocol):
    """Protocol for JIRAReporterService."""

    async def submit_report(self, report_data: Dict[str, Any]) -> Dict[str, Any]: ...


class StatusCommandServiceProtocol(Protocol):
    """Protocol for StatusCommandService."""

    async def execute_status_command(
        self, command: str, user_id: str, channel_id: str
    ) -> Dict[str, Any]: ...

    async def get_service_health(self) -> Dict[str, str]: ...

    async def get_system_metrics(self) -> Dict[str, Any]: ...


class KetchupAIServiceProtocol(Protocol):
    """Protocol for KetchupAIService."""

    async def generate_response(self, prompt: str, context: Dict[str, Any] = None) -> str: ...

    async def analyze_sentiment(self, text: str) -> Dict[str, Any]: ...

    async def extract_keywords(self, text: str) -> List[str]: ...

    async def classify_message(self, message: str) -> str: ...


class AccessServiceProtocol(Protocol):
    """Protocol for AccessService."""

    async def request_access(
        self, user_id: str, channel_id: str, justification: str = None
    ) -> AccessRequest: ...

    async def approve_access(self, request_id: str, approver_id: str) -> AccessRequest: ...

    async def deny_access(
        self, request_id: str, approver_id: str, reason: str = None
    ) -> AccessRequest: ...

    async def check_access(self, user_id: str, channel_id: str) -> bool: ...

    async def get_pending_requests(self) -> List[AccessRequest]: ...


class ChannelInfoOpsServiceProtocol(Protocol):
    """Protocol for ChannelInfoOpsService."""

    async def get_channel_info(self, channel_id: str) -> Optional[ChannelInfoOps]: ...

    async def update_channel_info(self, channel_id: str, info: ChannelInfoOps) -> bool: ...

    async def delete_channel_info(self, channel_id: str) -> bool: ...

    async def list_all_channel_info(self) -> List[ChannelInfoOps]: ...

    async def bulk_update_channel_info(self, updates: List[Tuple[str, ChannelInfoOps]]) -> int: ...


class JiraValidationServiceProtocol(Protocol):
    """Protocol for JiraValidationService."""

    def validate_project_key(self, project_key: str) -> ValidationResult: ...

    def validate_issue_type(self, project_key: str, issue_type: str) -> ValidationResult: ...

    def validate_user(self, username: str) -> ValidationResult: ...

    def validate_epic_link(self, epic_key: str) -> ValidationResult: ...

    def validate_priority(self, priority: str) -> ValidationResult: ...

    def validate_component(self, project_key: str, component: str) -> ValidationResult: ...

    def validate_version(self, project_key: str, version: str) -> ValidationResult: ...


class RateLimiterProtocol(Protocol):
    """Protocol for RateLimiter."""

    async def check_rate_limit(self, key: str) -> RateLimitResult: ...

    async def increment_counter(self, key: str) -> None: ...

    async def reset_counter(self, key: str) -> None: ...

    async def get_remaining_calls(self, key: str) -> int: ...


class FeatureServiceProtocol(Protocol):
    """Protocol for FeatureService."""

    async def handle_feature_command(self, params: FeatureCommandParams) -> Dict[str, Any]: ...

    def is_feature_enabled(self, feature_name: str) -> bool: ...

    def get_feature_config(self, feature_name: str) -> Dict[str, Any]: ...


class JoinNotificationOpsProtocol(Protocol):
    """Protocol for JoinNotificationOps."""

    async def track_notification(self, tracking_data: Dict[str, Any]) -> bool: ...

    async def get_channel_stats(self, channel_id: str) -> Dict[str, Any]: ...

    async def get_weekly_report(self, week_key: str) -> Dict[str, Any]: ...


class MetricsDataCollectorProtocol(Protocol):
    """Protocol for metrics data collection."""

    async def collect_cso_metrics(self) -> Dict[str, Any]:
        """Collect executive CSO management metrics."""
        ...

    async def collect_technical_metrics(self) -> Dict[str, Any]:
        """Collect technical system health metrics."""
        ...

    async def collect_all_metrics(self) -> Dict[str, Any]:
        """Collect all metrics for dashboard."""
        ...


class ChannelEligibilityServiceProtocol(Protocol):
    """Protocol for ChannelEligibilityService."""

    async def is_channel_eligible(
        self, channel_id: str, user_id: str, response_url: Optional[str] = None
    ) -> Tuple[bool, Optional[str]]: ...

    async def handle_ineligible_channel(
        self,
        channel_id: str,
        inviter_id: str,
        reason: str,
    ) -> None: ...


class ListCommandProtocol(Protocol):
    """Protocol for SlackListCommand."""

    async def process_list_params(
        self,
        params: Any,
        user_id: str,
        incoming_channel: str,
        response_url: str,
    ) -> Optional[Dict[str, Any]]: ...


class QueryCommandProtocol(Protocol):
    """Protocol for SlackQueryHandler."""

    async def process_query_request(
        self,
        params: Any,
        user_id: str,
        channel_id: Optional[str] = None,
        dm_channel_id: Optional[str] = None,
        incoming_channel: Optional[str] = None,
        response_url: Optional[str] = None,
        user_name: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]: ...


class SummaryCommandProtocol(Protocol):
    """Protocol for SlackSummaryHandler."""

    async def process_summary_params(
        self,
        params: Any,
        user_id: str,
        channel_id: Optional[str] = None,
        dm_channel_id: Optional[str] = None,
        response_url: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]: ...


class StatusReportCommandProtocol(Protocol):
    """Protocol for SlackReports."""

    async def process_status_request(
        self,
        command_verified: str,
        text: str,
        user_id: str,
        incoming_channel: str,
        dm_channel_id: Optional[str] = None,
        response_url: Optional[str] = None,
        channel_id: Optional[str] = None,
        user_name: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]: ...

    async def process_report_request(
        self,
        command_verified: str,
        text: str,
        user_id: str,
        incoming_channel: str,
        dm_channel_id: Optional[str] = None,
        response_url: Optional[str] = None,
        channel_id: Optional[str] = None,
        user_name: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]: ...


class ArchiveCommandProtocol(Protocol):
    """Protocol for SlackArchiveCommand."""

    async def process_archive_params(
        self,
        params: Any,
        user_id: str,
        incoming_channel: str,
        response_url: Optional[str] = None,
    ) -> None: ...
