# Slack-specific protocols for typed DI migration
# DO NOT EDIT - Generated by extract_service_interfaces.py

from typing import Protocol, Any, Dict, List, Union, Optional
from datetime import datetime

# Placeholder types for missing dependencies - fallback to Any for all undefined types
SlackConfig = Any
SlackPostingHandler = Any
CommandParams = Any
FeatureCommandParams = Any

class SlackUserStoreProtocol(Protocol):
    """Protocol for SlackUserStore."""

    async def get_user_info(self, user_id: str) -> Dict[str, Any]: ...

    async def clear_user_cache(self) -> None: ...

    async def get_users_display_name(self, user_id: str) -> str: ...

    def set_client(self, client: Any) -> None: ...


class SlackWebClientProtocol(Protocol):
    """Protocol for SlackWebClient."""

    async def chat_postMessage(self, **kwargs) -> Dict[str, Any]: ...

    async def conversations_list(self, **kwargs) -> Dict[str, Any]: ...

    async def conversations_info(self, **kwargs) -> Dict[str, Any]: ...

    async def users_info(self, **kwargs) -> Dict[str, Any]: ...

    async def views_publish(self, **kwargs) -> Dict[str, Any]: ...

    async def views_update(self, **kwargs) -> Dict[str, Any]: ...

    async def chat_update(self, **kwargs) -> Dict[str, Any]: ...

    async def conversations_members(self, **kwargs) -> Dict[str, Any]: ...

    async def users_list(self, **kwargs) -> Dict[str, Any]: ...

    async def conversations_join(self, **kwargs) -> Dict[str, Any]: ...

    async def chat_delete(self, **kwargs) -> Dict[str, Any]: ...

    async def reactions_add(self, **kwargs) -> Dict[str, Any]: ...

    async def files_upload_v2(self, **kwargs) -> Dict[str, Any]: ...


class KetchupSlackServiceProtocol(Protocol):
    """Protocol for KetchupSlackService."""

    async def handle_event(self, event_data: Dict[str, Any]) -> Dict[str, Any]: ...

    async def send_message(self, channel: str, text: str, blocks: List[Dict[str, Any]] = None) -> Dict[str, Any]: ...

    async def update_message(self, channel: str, ts: str, text: str, blocks: List[Dict[str, Any]] = None) -> Dict[str, Any]: ...

    async def delete_message(self, channel: str, ts: str) -> Dict[str, Any]: ...

    async def get_channel_info(self, channel: str) -> Dict[str, Any]: ...

    async def get_user_info(self, user: str) -> Dict[str, Any]: ...

    async def upload_file(self, channels: Union[str, List[str]], file: Any, title: str = None, initial_comment: str = None) -> Dict[str, Any]: ...


class SlackPostingHandlerProtocol(Protocol):
    """Protocol for SlackPostingHandler."""

    async def post_message(self, channel: str, message: str, blocks: List[Dict[str, Any]] = None) -> Dict[str, Any]: ...

    async def post_ephemeral(self, channel: str, user: str, message: str, blocks: List[Dict[str, Any]] = None) -> Dict[str, Any]: ...

    async def update_message(self, channel: str, ts: str, message: str, blocks: List[Dict[str, Any]] = None) -> Dict[str, Any]: ...

    async def delete_message(self, channel: str, ts: str) -> Dict[str, Any]: ...

    async def upload_file(self, channels: Union[str, List[str]], file_content: bytes, filename: str, title: str = None, initial_comment: str = None) -> Dict[str, Any]: ...


class HomeTabHandlerProtocol(Protocol):
    """Protocol for HomeTabHandler."""

    async def build_home_tab(self, user_id: str) -> Dict[str, Any]: ...

    async def handle_home_tab_event(self, event: Dict[str, Any]) -> Dict[str, Any]: ...

    async def refresh_home_tab(self, user_id: str) -> None: ...


class MessageHandlerProtocol(Protocol):
    """Protocol for MessageHandler."""

    async def handle_message(self, message_data: Dict[str, Any]) -> Dict[str, Any]: ...

    async def handle_app_mention(self, mention_data: Dict[str, Any]) -> Dict[str, Any]: ...

    async def handle_direct_message(self, dm_data: Dict[str, Any]) -> Dict[str, Any]: ...


class CommandHandlerProtocol(Protocol):
    """Protocol for CommandHandler."""

    async def handle_slash_command(self, command_data: Dict[str, Any]) -> Dict[str, Any]: ...

    async def execute_command(self, command: str, params: CommandParams) -> Dict[str, Any]: ...

    def get_command_help(self, command: str = None) -> str: ...


class InteractiveHandlerProtocol(Protocol):
    """Protocol for InteractiveHandler."""

    async def handle_button_click(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...

    async def handle_select_menu(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...

    async def handle_modal_submission(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...

    async def handle_view_closed(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...


class EventHandlerProtocol(Protocol):
    """Protocol for EventHandler."""

    async def handle_channel_created(self, event: Dict[str, Any]) -> None: ...

    async def handle_channel_deleted(self, event: Dict[str, Any]) -> None: ...

    async def handle_channel_renamed(self, event: Dict[str, Any]) -> None: ...

    async def handle_member_joined_channel(self, event: Dict[str, Any]) -> None: ...

    async def handle_member_left_channel(self, event: Dict[str, Any]) -> None: ...


class FlagReviewApiClientProtocol(Protocol):
    """Protocol for FlagReviewApiClient."""

    async def display_modal_via_api(
        self, trigger_id: str, modal_view: Dict[str, Any], modal_type: str
    ) -> bool: ...

    async def get_conversation_history(
        self, channel_id: str, message_ts: str, limit: int = 1
    ) -> Optional[Dict[str, Any]]: ...

    async def store_command_flag(
        self,
        channel_id: str,
        command_execution_id: str,
        user_id: str,
        user_name: str,
        original_text: str,
        command_type: str,
        original_channel: str,
    ) -> bool: ...

    async def get_command_output(self, command_execution_id: str) -> Optional[str]: ...

    async def get_feedback_data(
        self, channel_id: str, message_ts: str
    ) -> Optional[Dict[str, Any]]: ...

    async def update_feedback_status(
        self, channel_id: str, message_ts: str, user_id: str, new_status: str
    ) -> bool: ...

    async def store_summary_review(
        self,
        channel_id: str,
        message_ts: str,
        user_id: str,
        user_name: str,
        original_text: str,
        review_reason: str,
        review_type: str = "summary",
    ) -> bool: ...

    async def update_command_feedback_status(
        self, channel_id: str, command_execution_id: str, user_id: str, new_status: str
    ) -> bool: ...


class NotificationSenderProtocol(Protocol):
    """Protocol for NotificationSender."""

    def create_new_flag_notification_blocks(
        self,
        channel_id: str,
        user_id: str,
        user_name: str,
        feedback_text: Optional[str],
    ) -> list: ...

    def create_escalation_notification_blocks(
        self, channel_id: str, user_id: str, feedback_text: Optional[str]
    ) -> list: ...

    async def send_dm_error(self, user_id: str, error_message: str) -> None: ...

    async def send_dm_confirmation(
        self, user_id: str, confirmation_message: str
    ) -> None: ...

    async def show_flag_details_in_dm(self, user_id: str, flag_id: str) -> None: ...

    async def handle_quick_reply_from_dm(
        self, payload: Dict[str, Any], flag_id: str
    ) -> None: ...

    async def send_notification_batch(
        self, notifications: list[Dict[str, Any]]
    ) -> Dict[str, bool]: ...

    def format_notification_timestamp(self, timestamp: Optional[str] = None) -> str: ...

    def create_notification_footer(self, notification_id: str) -> Dict[str, Any]: ...


class ReviewPosterProtocol(Protocol):
    """Protocol for ReviewPoster."""

    async def post_review_summary(
        self,
        channel_id: str,
        flag_count: int,
        acknowledged_count: int,
        replied_count: int,
        period: str = "week",
    ) -> bool: ...

    def format_review_message(
        self,
        feedback_text: str,
        user_id: str,
        channel_id: str,
        timestamp: str,
        include_actions: bool = True,
    ) -> str: ...

    def create_flag_review_blocks(
        self,
        channel_id: str,
        user_id: str,
        user_name: str,
        feedback_text: str,
        validation_issues: List[str],
        time_str: str,
        message_ts: Optional[str] = None,
        status_text: Optional[str] = None,
    ) -> List[Dict[str, Any]]: ...

    async def post_review_to_channel(
        self,
        channel_id: str,
        review_data: Dict[str, Any],
        post_to_review_channel: bool = True,
    ) -> Optional[str]: ...

    async def generate_weekly_report(
        self, start_date: datetime, end_date: datetime
    ) -> Dict[str, Any]: ...

    def create_review_trend_blocks(
        self, trend_data: Dict[str, Any]
    ) -> List[Dict[str, Any]]: ...


class BlockBuilderProtocol(Protocol):
    """Protocol for BlockBuilder."""

    def _create_command_feedback_modal_view(
        self,
        channel_id: str,
        command_execution_id: str,
        command_type: str,
        original_channel: str,
    ) -> Dict[str, Any]: ...

    def _create_command_review_blocks(
        self,
        channel_id: str,
        command_execution_id: str,
        command_type: str,
        user_id: str,
        feedback_text: str,
        command_output: Optional[str],
        validation_issues: List[str],
    ) -> List[Dict[str, Any]]: ...

    def _create_command_output_blocks(
        self, command_output: str
    ) -> List[Dict[str, Any]]: ...

    def _create_validation_warning_block(
        self, validation_issues: List[str]
    ) -> Dict[str, Any]: ...

    def _create_command_action_buttons(
        self, channel_id: str, command_execution_id: str, user_id: str
    ) -> Dict[str, Any]: ...

    def _create_text_only_flag_message(
        self,
        command_type: str,
        channel_id: str,
        user_id: str,
        feedback_text: str,
        command_output: str,
        validation_issues: List[str],
    ) -> str: ...

    def _create_summary_review_blocks(
        self,
        channel_id: str,
        message_ts: str,
        user_id: str,
        feedback_text: str,
        validation_issues: List[str],
    ) -> List[Dict[str, Any]]: ...

    def _create_summary_action_buttons(
        self, channel_id: str, message_ts: str, user_id: str
    ) -> Dict[str, Any]: ...


class CommandFlagProcessorProtocol(Protocol):
    """Protocol for command flag processing functionality."""

    async def process_command_flag_action(self, payload: Dict[str, Any]) -> bool: ...

    async def handle_command_flag_button_click(self, payload: Dict[str, Any]) -> bool: ...

    async def handle_command_flag_submission(self, payload: Dict[str, Any]) -> bool: ...

    async def handle_command_acknowledgment(self, payload: Dict[str, Any]) -> bool: ...

    async def handle_command_reply_button_click(self, payload: Dict[str, Any]) -> bool: ...

    async def handle_command_reply_submission(self, payload: Dict[str, Any]) -> bool: ...


class SlackEventHandlerProtocol(Protocol):
    """Protocol for SlackEventHandler."""

    async def handle_channel_created(
        self, event: dict, response_url: Optional[str] = None
    ) -> None: ...

    async def handle_member_joined_channel(
        self, event: dict, response_url: Optional[str] = None
    ) -> None: ...

    async def handle_channel_archive(self, event: dict) -> None: ...

    async def handle_channel_unarchive(self, event: dict) -> None: ...

    async def handle_app_mention(self, event: dict) -> None: ...

    async def handle_message(self, event: dict) -> None: ...

    async def handle_message_im(self, event: dict) -> None: ...