"""
Unit tests for the JIRA reporter report generator.

Tests the ReportGenerator class that generates incident reports from archived
channel messages using AI.
"""

from unittest.mock import AsyncMock, MagicMock

import pytest

from ketchup_unified_scheduler.services.jira_reporter.report_generator import ReportGenerator


class TestReportGenerator:
    """Test the ReportGenerator functionality."""

    @pytest.fixture
    def mock_openai_handler(self):
        """Create a mock OpenAI handler."""
        handler = MagicMock()
        handler.execute_prompt = AsyncMock()
        return handler

    @pytest.fixture
    def mock_channel_msg_ops(self):
        """Create a mock channel message operations."""
        ops = MagicMock()
        ops.fetch_channel_messages = AsyncMock()
        return ops

    @pytest.fixture
    def report_generator(self, mock_openai_handler, mock_channel_msg_ops):
        """Create a ReportGenerator instance with mocked dependencies."""
        return ReportGenerator(
            openai_handler=mock_openai_handler, channel_msg_ops=mock_channel_msg_ops
        )

    @pytest.fixture
    def sample_messages(self):
        """Sample Slack messages for testing (already formatted as strings)."""
        return [
            "[2024-01-01 00:00:00 UTC] User U123: We're seeing authentication errors",
            "[2024-01-01 00:01:00 UTC] User U456: Looking into it now",
            "[2024-01-01 00:02:00 UTC] User U123: Found the issue - certificate expired",
        ]

    @pytest.fixture
    def sample_channel_metadata(self):
        """Sample channel metadata for testing."""
        return {
            "channel_id": "C123456",
            "channel_name": "cso_202401010001_adobe_campaign_12345",
            "customer_name": "Adobe Campaign",
            "jira_ticket": "CPGNREQ-12345",
        }

    @pytest.mark.asyncio
    async def test_generate_report_success(
        self,
        report_generator,
        mock_openai_handler,
        mock_channel_msg_ops,
        sample_messages,
        sample_channel_metadata,
    ):
        """Test successful report generation."""
        # Arrange
        mock_channel_msg_ops.fetch_channel_messages.return_value = sample_messages
        mock_ai_response = """
h3. Executive Summary
Authentication service experienced certificate expiration causing login failures.

h3. People Involved
- U123: Identified the issue
- U456: Investigated the problem

h3. Incident Timeline
- 2024-01-01 00:00:00 UTC: Authentication errors reported
- 2024-01-01 00:01:00 UTC: Investigation started
- 2024-01-01 00:02:00 UTC: Root cause identified - expired certificate
"""
        mock_openai_handler.execute_prompt.return_value = mock_ai_response

        # Act
        result = await report_generator.generate_report(
            channel_id=sample_channel_metadata["channel_id"],
            channel_metadata=sample_channel_metadata,
        )

        # Assert
        assert result is not None
        assert "h2. Ketchup Automated Incident Report" in result
        assert "Adobe Campaign" in result
        assert "CPGNREQ-12345" in result
        assert "Executive Summary" in result
        assert "automatically generated by Ketchup" in result

        # Verify channel messages were fetched
        mock_channel_msg_ops.fetch_channel_messages.assert_called_once_with(
            channel_id="C123456", limit=500
        )

        # Verify AI was called with proper parameters
        mock_openai_handler.execute_prompt.assert_called_once()
        ai_call_args = mock_openai_handler.execute_prompt.call_args
        assert ai_call_args.kwargs["max_tokens"] == 2000
        assert ai_call_args.kwargs["reasoning_effort"] == "medium"

    @pytest.mark.asyncio
    async def test_generate_report_no_messages(
        self, report_generator, mock_channel_msg_ops, sample_channel_metadata
    ):
        """Test report generation when no messages are found."""
        # Arrange
        mock_channel_msg_ops.fetch_channel_messages.return_value = []

        # Act
        result = await report_generator.generate_report(
            channel_id=sample_channel_metadata["channel_id"],
            channel_metadata=sample_channel_metadata,
        )

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_generate_report_ai_failure(
        self,
        report_generator,
        mock_openai_handler,
        mock_channel_msg_ops,
        sample_messages,
        sample_channel_metadata,
    ):
        """Test report generation when AI fails to generate response."""
        # Arrange
        mock_channel_msg_ops.fetch_channel_messages.return_value = sample_messages
        mock_openai_handler.execute_prompt.return_value = None  # AI failure

        # Act
        result = await report_generator.generate_report(
            channel_id=sample_channel_metadata["channel_id"],
            channel_metadata=sample_channel_metadata,
        )

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_generate_report_handles_exceptions(
        self, report_generator, mock_channel_msg_ops, sample_channel_metadata
    ):
        """Test exception handling during report generation."""
        # Arrange
        mock_channel_msg_ops.fetch_channel_messages.side_effect = Exception("API Error")

        # Act
        result = await report_generator.generate_report(
            channel_id=sample_channel_metadata["channel_id"],
            channel_metadata=sample_channel_metadata,
        )

        # Assert
        assert result is None

    def test_format_messages_for_ai(self, report_generator, sample_messages):
        """Test message formatting for AI consumption."""
        # Act
        result = report_generator._format_messages_for_ai(sample_messages)

        # Assert
        assert "[2024-01-01 00:00:00 UTC] User U123: We're seeing authentication errors" in result
        assert "[2024-01-01 00:01:00 UTC] User U456: Looking into it now" in result
        assert (
            "[2024-01-01 00:02:00 UTC] User U123: Found the issue - certificate expired" in result
        )

    def test_format_messages_filters_bot_messages(self, report_generator):
        """Test that bot messages are filtered out."""
        # Arrange - messages should be pre-formatted strings
        messages = [
            "[2024-01-01 00:00:00 UTC] User U123: Human message",
            "[2024-01-01 00:01:00 UTC] User U456: Bot message",
        ]

        # Act
        result = report_generator._format_messages_for_ai(messages)

        # Assert
        assert "Human message" in result
        assert "Bot message" in result  # Note: filtering should happen before this method

    def test_create_report_prompt(self, report_generator, sample_channel_metadata):
        """Test report prompt creation."""
        # Arrange
        formatted_messages = "Test messages"

        # Act
        result = report_generator._create_report_prompt(
            formatted_messages=formatted_messages,
            channel_metadata=sample_channel_metadata,
        )

        # Assert
        assert "Customer: Adobe Campaign" in result
        assert "JIRA Ticket: CPGNREQ-12345" in result
        assert "cso_202401010001_adobe_campaign_12345" in result
        assert "Test messages" in result
        assert "h3. Executive Summary" in result
        assert "h3. People Involved" in result
        assert "h3. Incident Timeline" in result
        # Verify XML-tagged structure
        assert "<role>" in result
        assert "<context>" in result
        assert "<response_structure>" in result
        assert "<data_source>" in result
        assert "<formatting_rules>" in result
        assert "<constraints>" in result

    def test_format_for_jira(self, report_generator, sample_channel_metadata):
        """Test JIRA markdown formatting."""
        # Arrange
        report_text = "Test report content"

        # Act
        result = report_generator._format_for_jira(
            report_text=report_text, channel_metadata=sample_channel_metadata
        )

        # Assert
        assert "h2. Ketchup Automated Incident Report" in result
        assert f"*Channel*: {sample_channel_metadata['channel_name']}" in result
        assert f"*Customer*: {sample_channel_metadata['customer_name']}" in result
        assert "Test report content" in result
        assert "This report was automatically generated by Ketchup" in result

        # Check timestamp format
        assert "*Generated*:" in result
        assert "UTC" in result

    def test_format_messages_handles_invalid_timestamps(self, report_generator):
        """Test handling of invalid timestamps in messages."""
        # Arrange - messages should be pre-formatted strings with timestamps already handled
        messages = [
            "[invalid] User U123: Message with invalid timestamp",
            "[unknown] User U456: Message with no timestamp",
        ]

        # Act
        result = report_generator._format_messages_for_ai(messages)

        # Assert
        assert "[invalid] User U123: Message with invalid timestamp" in result
        assert "[unknown] User U456: Message with no timestamp" in result

    def test_create_report_prompt_without_json_flag(
        self, report_generator, sample_channel_metadata, monkeypatch
    ):
        """
        Test that prompt does NOT contain 'json' keyword when feature flag is disabled.

        This test replicates the 400 error condition:
        Azure OpenAI API returns 400 if response_format is json_object but prompt
        doesn't contain the word "json" in any form.
        """
        # Arrange
        from packages.core.config.feature_flags import FeatureFlags

        # Mock feature flag to return False (JSON mode disabled)
        monkeypatch.setattr(FeatureFlags, "is_structured_json_output_enabled", lambda: False)
        formatted_messages = "Test messages"

        # Act
        result = report_generator._create_report_prompt(
            formatted_messages=formatted_messages,
            channel_metadata=sample_channel_metadata,
        )

        # Assert - prompt should NOT contain "json" when flag is disabled
        assert "json" not in result.lower()
        assert "JSON" not in result
        # Still has all the normal prompt content
        assert "JIRA Ticket: CPGNREQ-12345" in result
        assert "Test messages" in result

    def test_create_report_prompt_with_json_flag_enabled(
        self, report_generator, sample_channel_metadata, monkeypatch
    ):
        """
        Test that prompt CONTAINS 'json' keyword when feature flag is enabled.

        This test verifies the fix for the 400 error:
        When KETCHUP_STRUCTURED_JSON_OUTPUT=true, the prompt must include "json"
        to satisfy Azure OpenAI API requirements for response_format: json_object.
        """
        # Arrange
        from packages.core.config.feature_flags import FeatureFlags

        # Mock feature flag to return True (JSON mode enabled)
        monkeypatch.setattr(FeatureFlags, "is_structured_json_output_enabled", lambda: True)
        formatted_messages = "Test messages"

        # Act
        result = report_generator._create_report_prompt(
            formatted_messages=formatted_messages,
            channel_metadata=sample_channel_metadata,
        )

        # Assert - prompt MUST contain "json" when flag is enabled
        assert "json" in result.lower() or "JSON" in result
        # Verify specific JSON instruction text is present
        assert "Return your response as JSON" in result
        assert '{"response_text"' in result
        # Still has all the normal prompt content
        assert "JIRA Ticket: CPGNREQ-12345" in result
        assert "Test messages" in result
