"""
Unit tests for the JIRA service.

Tests the JiraService class that posts reports to JIRA tickets via MCP.
Uses test tickets: CPGNREQ-180248 and CSOPM-59374
"""

import os
from unittest.mock import AsyncMock, MagicMock, patch

import httpx
import pytest

from jira_reporter.jira_service import JiraService


def create_mcp_response(data):
    """Helper function to create MCP protocol JSON-RPC response."""
    return {"result": data}


def create_mcp_error(code, message):
    """Helper function to create MCP protocol JSON-RPC error response."""
    return {"error": {"code": code, "message": message}}


class TestJiraService:
    """Test the JiraService functionality."""

    # Test JIRA tickets provided for testing
    TEST_TICKET_CPGNREQ = "CPGNREQ-180248"
    TEST_TICKET_CSOPM = "CSOPM-59374"

    @pytest.fixture
    def mock_secrets_manager(self):
        """Create a mock secrets manager."""
        manager = MagicMock()
        return manager

    @pytest.fixture
    def mock_ims_token_manager(self):
        """Create a mock IMS token manager."""
        manager = MagicMock()
        manager.get_valid_token = AsyncMock(return_value="mock_token_123")
        return manager

    @pytest.fixture
    def jira_service(self, mock_secrets_manager, mock_ims_token_manager):
        """Create a JiraService instance with mocked dependencies."""
        return JiraService(
            secrets_manager=mock_secrets_manager, ims_token_manager=mock_ims_token_manager
        )

    @pytest.fixture
    def sample_report(self):
        """Sample report text for testing."""
        return """h2. Ketchup Automated Incident Report

*Channel*: cso_202401010001_test_12345
*Customer*: Test Customer
*Generated*: 2024-01-01 00:00:00 UTC

----

h3. Executive Summary
Test incident report for automated JIRA posting.

h3. Resolution
Issue resolved by restarting service.

----

_This report was automatically generated by Ketchup when the channel was archived._"""

    @pytest.mark.asyncio
    async def test_post_comment_success(self, jira_service, sample_report):
        """Test successful comment posting to JIRA."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock successful ticket validation and comment posting (JSON-RPC responses)
            mock_client.post.side_effect = [
                # First call: ticket validation
                AsyncMock(
                    status_code=200,
                    json=lambda: {
                        "result": {
                            "content": [
                                {
                                    "text": '{"total": 1, "issues": [{"key": "'
                                    + self.TEST_TICKET_CPGNREQ
                                    + '"}]}'
                                }
                            ]
                        }
                    },
                ),
                # Second call: comment posting
                AsyncMock(
                    status_code=200,
                    json=lambda: {"result": {"content": [{"text": "Comment added successfully"}]}},
                ),
            ]

            # Act
            result = await jira_service.post_comment_to_ticket(
                jira_ticket_id=self.TEST_TICKET_CPGNREQ, comment_text=sample_report
            )

            # Assert
            assert result is True

            # Verify both API calls were made
            assert mock_client.post.call_count == 2

            # Verify first call (ticket validation)
            first_call = mock_client.post.call_args_list[0]
            assert "/message" in first_call.args[0]
            validation_payload = first_call.kwargs["json"]
            assert validation_payload["method"] == "tools/call"
            assert validation_payload["params"]["name"] == "search_jira_issues"

            # Verify second call (comment posting)
            second_call = mock_client.post.call_args_list[1]
            assert "/message" in second_call.args[0]
            comment_payload = second_call.kwargs["json"]
            assert comment_payload["method"] == "tools/call"
            assert comment_payload["params"]["name"] == "add_jira_comment"
            assert (
                comment_payload["params"]["arguments"]["issueIdOrKey"] == self.TEST_TICKET_CPGNREQ
            )
            assert comment_payload["params"]["arguments"]["comment"]["body"] == sample_report

    @pytest.mark.asyncio
    async def test_post_comment_ticket_not_found(self, jira_service, sample_report):
        """Test comment posting when ticket doesn't exist."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock ticket validation failure - empty results
            mock_client.post.return_value = AsyncMock(
                status_code=200,
                json=lambda: {"result": {"content": [{"text": '{"total": 0, "issues": []}'}]}},
            )

            # Act
            result = await jira_service.post_comment_to_ticket(
                jira_ticket_id="INVALID-99999", comment_text=sample_report
            )

            # Assert
            assert result is False

            # Verify only validation was called, not comment posting
            assert mock_client.post.call_count == 1

    @pytest.mark.asyncio
    async def test_post_comment_empty_ticket_id(self, jira_service, sample_report):
        """Test comment posting with empty ticket ID."""
        # Act
        result = await jira_service.post_comment_to_ticket(
            jira_ticket_id="", comment_text=sample_report
        )

        # Assert
        assert result is False

    @pytest.mark.asyncio
    async def test_post_comment_strips_url_parts(self, jira_service, sample_report):
        """Test that ticket ID is normalized from URLs."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock successful ticket validation and comment posting
            mock_client.post.side_effect = [
                # First call: ticket validation
                AsyncMock(
                    status_code=200,
                    json=lambda: {
                        "result": {
                            "content": [
                                {
                                    "text": '{"total": 1, "issues": [{"key": "'
                                    + self.TEST_TICKET_CSOPM
                                    + '"}]}'
                                }
                            ]
                        }
                    },
                ),
                # Second call: comment posting
                AsyncMock(
                    status_code=200,
                    json=lambda: {"result": {"content": [{"text": "Comment added successfully"}]}},
                ),
            ]

            # Act - Pass full JIRA URL
            result = await jira_service.post_comment_to_ticket(
                jira_ticket_id=f"https://jira.corp.adobe.com/browse/{self.TEST_TICKET_CSOPM}",
                comment_text=sample_report,
            )

            # Assert
            assert result is True

            # Verify normalized ticket ID was used in both calls
            first_call = mock_client.post.call_args_list[0]
            validation_payload = first_call.kwargs["json"]
            assert self.TEST_TICKET_CSOPM in validation_payload["params"]["arguments"]["jql"]

            second_call = mock_client.post.call_args_list[1]
            comment_payload = second_call.kwargs["json"]
            assert comment_payload["params"]["arguments"]["issueIdOrKey"] == self.TEST_TICKET_CSOPM

    @pytest.mark.asyncio
    async def test_post_comment_api_error(self, jira_service, sample_report):
        """Test handling of API errors during comment posting."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock successful validation but failed comment posting
            mock_client.post.side_effect = [
                # First call: successful ticket validation
                AsyncMock(
                    status_code=200,
                    json=lambda: {
                        "result": {
                            "content": [
                                {
                                    "text": '{"total": 1, "issues": [{"key": "'
                                    + self.TEST_TICKET_CPGNREQ
                                    + '"}]}'
                                }
                            ]
                        }
                    },
                ),
                # Second call: API error during comment posting
                AsyncMock(status_code=500, text="Internal Server Error"),
            ]

            # Act
            result = await jira_service.post_comment_to_ticket(
                jira_ticket_id=self.TEST_TICKET_CPGNREQ, comment_text=sample_report
            )

            # Assert
            assert result is False

    @pytest.mark.asyncio
    async def test_post_comment_network_exception(self, jira_service, sample_report):
        """Test handling of network exceptions."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock network error during validation
            mock_client.post.side_effect = httpx.NetworkError("Connection failed")

            # Act
            result = await jira_service.post_comment_to_ticket(
                jira_ticket_id=self.TEST_TICKET_CPGNREQ, comment_text=sample_report
            )

            # Assert
            assert result is False

    @pytest.mark.asyncio
    async def test_validate_ticket_exists(self, jira_service):
        """Test ticket validation method."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock successful ticket search via MCP
            mock_client.post.return_value = AsyncMock(
                status_code=200,
                json=lambda: create_mcp_response(
                    {
                        "content": [
                            {
                                "text": f'{{"total": 1, "issues": [{{"key": "{self.TEST_TICKET_CSOPM}"}}]}}'
                            }
                        ]
                    }
                ),
            )

            # Act
            result = await jira_service._validate_ticket_exists(self.TEST_TICKET_CSOPM)

            # Assert
            assert result is True

            # Verify correct MCP endpoint and payload was called
            post_call = mock_client.post.call_args
            assert "/message" in post_call.args[0]
            payload = post_call.kwargs["json"]
            assert payload["method"] == "tools/call"
            assert payload["params"]["name"] == "search_jira_issues"
            assert f"key = {self.TEST_TICKET_CSOPM}" in payload["params"]["arguments"]["jql"]

    @pytest.mark.asyncio
    async def test_validate_ticket_not_exists(self, jira_service):
        """Test ticket validation for non-existent ticket."""
        # Arrange
        with patch("httpx.AsyncClient") as mock_client_class:
            mock_client = AsyncMock()
            mock_client_class.return_value.__aenter__.return_value = mock_client

            # Mock ticket validation failure - no results found
            mock_client.post.return_value = AsyncMock(
                status_code=200,
                json=lambda: create_mcp_response(
                    {"content": [{"text": '{"total": 0, "issues": []}'}]}
                ),
            )

            # Act
            result = await jira_service._validate_ticket_exists("INVALID-99999")

            # Assert
            assert result is False

    @pytest.mark.asyncio
    async def test_get_headers(self, jira_service):
        """Test header generation for MCP JIRA."""
        # Act
        headers = await jira_service._get_headers()

        # Assert
        assert headers["Content-Type"] == "application/json"

    def test_mcp_base_url_from_environment(self, mock_secrets_manager, mock_ims_token_manager):
        """Test that MCP base URL is configurable via environment."""
        # Arrange
        test_url = "http://test-mcp:9999"
        with patch.dict(os.environ, {"MCP_BASE_URL": test_url}):
            # Act
            service = JiraService(
                secrets_manager=mock_secrets_manager, ims_token_manager=mock_ims_token_manager
            )

            # Assert
            assert service.mcp_base_url == test_url

    def test_mcp_base_url_default(self, mock_secrets_manager, mock_ims_token_manager):
        """Test default MCP base URL."""
        # Arrange
        with patch.dict(os.environ, {}, clear=True):
            # Act
            service = JiraService(
                secrets_manager=mock_secrets_manager, ims_token_manager=mock_ims_token_manager
            )

            # Assert
            assert service.mcp_base_url == "http://mcp-jira:8081"
