#!/bin/bash
# Quick checklist to verify Slack app configuration

echo "=========================================="
echo "Slack App Configuration Checklist"
echo "=========================================="
echo ""
echo "Open https://api.slack.com/apps and verify:"
echo ""

echo "1. APP INSTALLATION"
echo "   ☐ Go to: Install App"
echo "   ☐ Status shows: 'Installed to [Your Workspace]'"
echo "   ☐ If not: Click 'Install to Workspace' → Authorize"
echo ""

echo "2. EVENT SUBSCRIPTIONS"
echo "   ☐ Go to: Event Subscriptions"
echo "   ☐ Toggle is: ON"
echo "   ☐ Request URL field is: EMPTY (or shows error - this is OK!)"
echo "   ☐ Bot events subscribed:"
echo "      ☐ app_mention"
echo "      ☐ message.channels"
echo "      ☐ message.groups"
echo "      ☐ message.im"
echo ""

echo "3. OAUTH SCOPES"
echo "   ☐ Go to: OAuth & Permissions"
echo "   ☐ Bot Token Scopes include:"
echo "      ☐ app_mentions:read"
echo "      ☐ chat:write"
echo "      ☐ commands"
echo "      ☐ channels:read"
echo "      ☐ users:read"
echo ""

echo "4. SOCKET MODE"
echo "   ☐ Go to: Socket Mode"
echo "   ☐ Toggle is: ON"
echo "   ☐ Shows: 'Socket Mode is enabled'"
echo ""

echo "5. APP-LEVEL TOKEN"
echo "   ☐ Go to: Basic Information → App-Level Tokens"
echo "   ☐ Token exists with scopes:"
echo "      ☐ connections:write (REQUIRED)"
echo "      ☐ authorizations:read (optional)"
echo ""

echo "6. SLASH COMMAND"
echo "   ☐ Go to: Slash Commands"
echo "   ☐ /maptimize command exists"
echo "   ☐ Request URL field is: EMPTY"
echo ""

echo "=========================================="
echo "TESTING"
echo "=========================================="
echo ""
echo "After verifying above, test in Slack:"
echo ""
echo "1. Try: @maptimize help"
echo "   Expected: Bot responds or you see activity in Docker logs"
echo ""
echo "2. Try: /maptimize"
echo "   Expected: Bot responds or shows 'dispatch_failed'"
echo ""
echo "3. Monitor logs:"
echo "   docker logs -f maptimize-bot"
echo "   Expected: See 'DEBUG: app_mention event received'"
echo ""

echo "=========================================="
echo "MOST COMMON FIX"
echo "=========================================="
echo ""
echo "If events still don't work after verifying above:"
echo ""
echo "1. Go to: OAuth & Permissions"
echo "2. Click: 'Reinstall to Workspace'"
echo "3. Authorize the app"
echo "4. Restart container: docker restart maptimize-bot"
echo "5. Test again"
echo ""

echo "=========================================="
echo "EVENT LOGS"
echo "=========================================="
echo ""
echo "To see what Slack is doing with events:"
echo ""
echo "1. Get your App ID from: https://api.slack.com/apps"
echo "   (Looks like: A09T3NE9WBB)"
echo ""
echo "2. Go to: https://api.slack.com/apps/[APP_ID]/event-subscriptions"
echo ""
echo "3. Scroll to 'Event Logs'"
echo ""
echo "4. Trigger an event (mention the bot)"
echo ""
echo "5. Check the log entry:"
echo "   - Event type: Should show 'app_mention' or 'slash_commands'"
echo "   - Delivery: Should show 'Socket Mode'"
echo "   - Status: Should show 'Delivered'"
echo ""
echo "If delivery shows 'HTTP 404' or URL: Request URL is configured (bad!)"
echo "If no events appear: App not installed or missing permissions"
echo ""
